apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch
  namespace: eck
spec:
  version: 9.0.0
  http:
    tls:
      selfSignedCertificate:
        disabled: true
  nodeSets:
    - name: masters
      count: 1
      config:
        node.store.allow_mmap: false
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
          spec:
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 5Gi
            storageClassName: do-block-storage
      podTemplate:
        metadata:
          labels:
            app: "elasticsearch"
            version: "8.15.0"
          annotations:
            traffic.sidecar.istio.io/includeInboundPorts: "*"
            # Port 443 is for installing Elasticsearch plugins
            traffic.sidecar.istio.io/excludeOutboundPorts: "9300,443"
            traffic.sidecar.istio.io/excludeInboundPorts: "9300"
        spec:
          automountServiceAccountToken: true
          containers:
            - name: elasticsearch
              resources:
                limits:
                  cpu: "0.5"
                  memory: "1Gi"
                requests:
                  cpu: "250m"
                  memory: "512Mi"
              env:
                - name: ES_JAVA_OPTS
                  value: "-Xms512m -Xmx512m"
              volumeMounts:
                - name: elasticsearch-data
                  mountPath: /usr/share/elasticsearch/data
          nodeSelector:
            nodepool: eck-np
  updateStrategy:
    changeBudget:
      maxSurge: 1
      maxUnavailable: 1