# Kibana Helm chart values

# Replicas
replicas: ${replicas}

# Security settings
securityContext:
  runAsUser: 1000
  fsGroup: 1000

# Kibana configuration
kibanaConfig:
  kibana.yml: |
    server.name: kibana
    server.host: "0.0.0.0"
    elasticsearch.hosts: ["http://elasticsearch-master:9200"]
    monitoring.ui.container.elasticsearch.enabled: true

# Ingress configuration
# Uncomment and modify as needed for your environment
# ingress:
#   enabled: true
#   annotations:
#     kubernetes.io/ingress.class: nginx
#     kubernetes.io/tls-acme: "true"
#   hosts:
#     - host: kibana.example.com
#       paths:
#         - path: /
#   tls:
#     - secretName: kibana-tls
#       hosts:
#         - kibana.example.com

# Resource limits are set in the Terraform configuration